### ISSUE TITLE
Another voice in favour...

### ISSUE THREAD

**Issue by andykirk** [WICG/cq-usecases#42]
Hi,

I find it a shame that not much is happening in this area. A while back I wrote this:

https://www.sitepoint.com/responsive-css-patterns-without-media-queries/

It didn't elicit much response (though it was referenced by Ethan Marcotte: https://ethanmarcotte.com/wrote/on-container-queries/), but I thought I'd post it here for prosterity.

Personally, I can't wait for Container Queries to be a reality, and though I understand there are some very complex issues involved, I wanted to add my voice to the "we need this" group.

Cheers,
Andy

**Comment by marcoscaceres** [comment]
We should gather these kinds of links in the wiki - with maybe "tl;dr" summary of key points. 

@andykirk, could you help start that off?: https://github.com/WICG/cq-usecases/wiki

**Comment by andykirk** [comment]
Happy to.
I’ll have a think about how best to organise them.

**Comment by marcoscaceres** [comment]
Here what I’ve been doing for Payments https://github.com/w3c/payment-request/wiki

**Comment by andykirk** [comment]
That's useful, thanks.

**Comment by eeeps** [comment]
@andykirk *huge* thanks for firing up a Wiki. I’ve added a couple of sections, myself, based on discussions in another issue... seems like there are a lot of things that belong more properly in a shared knowledge base, rather than in issues.

Your article is going to be particularly helpful as we sketch out the limitations of current approaches, which should be a key part of the Use Cases doc. Any chance you could distill all of your experiences and experiments into a first stab at a section modeled after [this one](http://usecases.responsiveimages.org/#limitations-of-current-techniques)?

(Oh and the mini-@marcoscaceres in my head just reminded me to ask you to [sign up as an official WICG member](https://www.w3.org/community/wicg/participants), if/before you do)

**Comment by andykirk** [comment]
Thanks @eeeps, I’m happy to give it a go. May not be for a few days though due to other commitments. Thanks for the heads-up about signing up to be a WICG member.

**Comment by eeeps** [comment]
I'll go ahead and close this issue, fire up a new one about a limitations section, and assign you.
