### ISSUE TITLE
need to decide on co-chairs

### ISSUE THREAD

**Issue by tantek** [WICG/cq-usecases#48]
Open issue / request / call as @marcoscaceres did in issue #44 
Currently @beep and @eeeps have volunteered, on the condition that they can reach out for help and mentorship (which I, as well as @marcoscaceres and other WICG co-chairs are happen to do).

**Comment by hereinthehive** [comment]
I first wrote a proof on concept of this kind of thing many years ago. If there’s a way I can help further conversations, I’d love to be involved

**Comment by beep** [comment]
Thanks, @tantek!

Are a (co-)chair’s responsibilities written down anywhere? That’d be really helpful to take a look at.

**Comment by tomhodgins** [comment]
I'm willing to help this initiative in any capacity, including this, if it helps get us toward a specification that can standardize this idea and move it forward!

I've been working on element queries research, creating plugins, and applying these concepts to sites I'm working on nearly daily since the end of 2014! I'm committed and invested to see the most come out of this standardization effort :D

**Comment by marcoscaceres** [comment]
@beep think of it as a "product/project management" role - key being that as Chairs, you and @eeeps:

 * support the Editor(s), by finding them reviewers, and solicit wider review from CSS Working Group, implementers, etc. along the way.
 * Manage the contributors, and repo (you have admin rights!).  
 * Make sure that you get new contributors to sign the IPR agreement. 
 * Help the community reach consensus (e.g., coordinating with implementers), and making sure impassioned discussions don't get out of hand (i.e., enforce the code of conduct!).
 * Keep the community informed of happenings (like @eeeps did - but also by reaching out to people writing about the topic and getting them involved and promoting their posts, etc.).
 * Generally, keep the project going and finding a way to make it a success. 
 * Channel the community's energy to positive things (e.g., we built responsiveimages.org as a community... that gave an outlet to many people in the community, and really helped make the project a success. It provided an alternative path for folks that wanted to help, but not directly on the standard.)

You can also see this [W3C guide](https://w3c.github.io/Guide/chair/role.html), but instead of liaising with W3C Staff, you will instead lease with the WICG Chairs. 

@tomhodgins, it would be best if you instead focus on Editing the spec. Part of editing involves also writing web platform tests. The whole thing takes a lot of time (with limited resources), so I want to make sure you don't get overburden. The editor naturally also ends up doing a bit of chairing; it's unavoidable, as your role is to capture both consensus and the technical solution - but at the same time, it makes it less stressful on you, as you can always ask the chairs to, for instance, find you a reviewer, or ping someone on the CSS Team at a browser company.

Hope that helps!

**Comment by marcoscaceres** [comment]
@hereinthehive, would be great to have you involved. Maybe you can support @tomhodgins with technical aspects and review?

**Comment by beep** [comment]
@marcoscaceres, this is massively helpful. I’ll take a look this week, and follow up with any questions. (@eeeps, if you want to chat directly, please drop me a line!)

**Comment by hereinthehive** [comment]
@marcoscaceres Yup - happy with that! Any way to help this forward...you can count me in. 

@tomhodgins: Let me know how I can best support you!

**Comment by beep** [comment]
For now, @eeeps and some @beep fellow will be acting as the project’s co-chairs. Marking this done!
