### ISSUE TITLE
London Meetup

### ISSUE THREAD

**Issue by ZeeCoder** [WICG/cq-usecases#51]
I'm not sure where else to discuss this: it seems I'll do a talk on container queries and how they work with react components.

If anyone has ideas on what I should not forget to mention, feel free to post a comment here.
I'll definitely talk about existing plugins, and about the movement at the WICG for example.

**Comment by ZeeCoder** [comment]
Here's a link to the meetup, it's very popular with developers queuing at the entrance every month:
https://react.london/

**Comment by eeeps** [comment]
*::wonders if we should start a Discourse or a Slack or something::*

**Edit**: or perhaps [a wiki](https://github.com/WICG/cq-usecases/wiki) will do?

**Comment by ZeeCoder** [comment]
I think using Slack is a fab idea!
It would be much easier to discuss stuff like this for example.

Which is definitely not fit for a wiki :D

**Comment by tomhodgins** [comment]
Discourse > Slack, as far as system resources go. Slack is a beast :'(

**Comment by ZeeCoder** [comment]
I usually run it in a tab and it's a-ok, but I'm on board with discord too

**Comment by ZeeCoder** [comment]
Ah wait, you said Discourse? I have no experience with that one :D

**Comment by ZeeCoder** [comment]
At a glance I would still prefer Discord, or Slack, but let's wait for others to chime in too. :D

**Comment by tomhodgins** [comment]
Whoops, I meant Discord 👀 I have just started using it because Slack was too heavy for my Macbook Air :/

**Comment by ZeeCoder** [comment]
In case someone's interested, I've sent in my abstract on what I'll try to fit in my 20m talk:
https://github.com/ZeeCoder/react-london-container-queries

On another note: shall we make a Discord channel then?
I'm not sure if we need it tbh, but worst case scenario we won't use it much. 🤔
/cc @eeeps @tomhodgins

**Comment by eeeps** [comment]
I went ahead and spun up [a Slack](https://containerqueries.slack.com). To signup, go [here](https://join.slack.com/t/containerqueries/shared_invite/enQtMzA2OTc5MDUwNjk1LTEwMWEzNjcwMTY1MGYzYWMyOGMxM2MzNDM1OGZjMjM3NDNiMDMxYTk0YjQxN2FjYTZkYmZkMDZmOWE1ODRkZWI).

Slack because:
1. I'm used it, and it was easy to set up.
2. I have zero data to back this up, but I *feel* like webby/engineer-y/design-y people are comfortable in it (whereas Discord looks (?) more catered to the gaming community (?))

@tomhodgins, I turned on the IRC and XMPP gateways to the channel, which should allow you to chat with a (much) lighter client, if you need to. I just tested it with IRC and while the setup was cumbersome (❤️ U IRC), it worked; here are [the docs](https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP); let me know if you need help setting that up.

@ZeeCoder awesome! I added your talk + a link to the abstract to the [minty-fresh Wiki](https://github.com/WICG/cq-usecases/wiki) that @andykirk [just set up](https://github.com/WICG/cq-usecases/issues/42#issuecomment-360032549), under an “Upcoming Events” heading. Looks like you’re off to an awesome start and I can’t wait to hear about (and hopefully see? are they recording?) the talk.

I’ll leave it up to you whether you want to leave this issue open for more visibility, or close it. But hopefully the Slack workspace provides a more appropriate place for discussion about community events and other such things that *aren’t* issues with the Use Cases and Requirements doc, going forward.

**Comment by ZeeCoder** [comment]
Maybe just put it on the wiki plus we can link it whenever we think we need to move a particular discussion there.
Thanks for the setup btw, I've joined now. 👍
I believe the talk should be available, but I'll double check.
